// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchDetails(arg1, arg2, arg3) {
  return window['go']['main']['App']['FetchDetails'](arg1, arg2, arg3);
}

export function GetColors() {
  return window['go']['main']['App']['GetColors']();
}

export function LoadColors() {
  return window['go']['main']['App']['LoadColors']();
}

export function SearchWord(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchWord'](arg1, arg2, arg3);
}
