// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchDetails(arg1:string,arg2:string,arg3:string):Promise<Array<main.WordDetails>>;

export function GetActiveColor():Promise<main.ColorScheme>;

export function GetColors():Promise<Array<main.ColorScheme>>;

export function LoadColors():Promise<void>;

export function SearchWord(arg1:string,arg2:string,arg3:string):Promise<Array<main.SearchResult>>;
